### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by jordan15** [eeoom/advanced_in_app_review#14]
Hello,

My error :
`Execution failed for task ':advanced_in_app_review:compileReleaseKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (1.8) and 'compileReleaseKotlin' (17).
`

I need for other plugin to use JVM17, with this error I'm unable to compile my flutter app.
Any idea

**Comment by hasanabbassorathiya** [comment]
Any updates?
