### ISSUE TITLE
I have used advanced_in_app_review plugin, but rating dialog not popup

### ISSUE THREAD

**Issue by branchdev98** [eeoom/advanced_in_app_review#2]
I have used advanced_in_app_review plugin, but rating dialog not popup
void initState() {
 super.initState();
//initPlatformState(),
 AdvancedInAppReview()
        .setMinDaysBeforeRemind(7)
        .setMinDaysAfterInstall(2)
        .setMinLaunchTimes(2)
        .monitor();
}
I removed initPlatformState() because it is useless.
now it seems that rating dialog not showing automatically, Should I add initPlatformState()?
or is it the issue of this plugin?

**Comment by eeoom** [comment]
In app reviews do not show up every time. The operating system decides when the alert is shown. The parameters of the plug in indicate only the minimum values before the system is asked to show the dialog, but as I said, the system decides afterwards if the dialog is shown.

Please note also that it is not shown in debug mode of android.
