### ISSUE TITLE
Update your package to be compatible with Flutter 3.0

### ISSUE THREAD

**Issue by ljsharp** [eeoom/advanced_in_app_review#3]
I saw an issue with your package like this

/C:/flutter/.pub-cache/hosted/pub.dartlang.org/advanced_in_app_review-1.0.5/lib/advanced_in_app_review.dart:41:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
    WidgetsBinding.instance?.addObserver(this);

Thanks

**Comment by eeoom** [comment]
Please try version 1.1.0, issue shloud be resolved in that release.

**Comment by ljsharp** [comment]
Yes it is resolved. Thanks 🙏🏾
