### ISSUE TITLE
Will it reset everytime i initialise

### ISSUE THREAD

**Issue by prakasharyaman** [eeoom/advanced_in_app_review#4]
my question is kind of a silly one but i just want to know that can i put the code : 
` AdvancedInAppReview()
      .setMinDaysBeforeRemind(7)
      .setMinDaysAfterInstall(2)
      .setMinLaunchTimes(2)
      .monitor();`

in `void main (){}` 

and will it remember the already fix value or will it move the days further every time the function is called 
ex: on **tuesday** its seven and on **wednesday** if i **recall** the function will it still be seven ?

**Comment by eeoom** [comment]
Hi!

No, nothing will be changed when calling the line of code multiple times. It only sets the triggers, according to some points in time. 

Best
Stefan
