### ISSUE TITLE
Is there's a way to test if the review is shown or not?

### ISSUE THREAD

**Issue by gupta-shrinath** [eeoom/advanced_in_app_review#5]
I know it depends on the OS in #2 but I want to test it.
In the debug build the following exception occur I'm not sure if this matters

<details>
<summary>Details</summary>

`I/InAppReviewPlugin(10008): onMethodCall: isAvailable
I/InAppReviewPlugin(10008): isAvailable: called
I/InAppReviewPlugin(10008): noContextOrActivity: called
I/InAppReviewPlugin(10008): isAvailable: playStoreInstalled: true
I/InAppReviewPlugin(10008): isAvailable: lollipopOrLater: true
I/InAppReviewPlugin(10008): isAvailable: The Play Store is available and Android 5 or later is being used
I/InAppReviewPlugin(10008): cacheReviewInfo: called
I/InAppReviewPlugin(10008): noContextOrActivity: called
I/PlayCore(10008): UID: [10157]  PID: [10008] ReviewService : requestInAppReview (droid.freelance.topup)
I/InAppReviewPlugin(10008): cacheReviewInfo: Requesting review flow
I/PlayCore(10008): UID: [10157]  PID: [10008] ReviewService : Initiate binding to the service.
I/OpenGLRenderer(10008): Davey! duration=721ms; Flags=1, IntendedVsync=2791677970829, Vsync=2792227970807, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=2792254764283, AnimationStart=2792254766220, PerformTraversalsStart=2792254766516, DrawStart=2792388436768, SyncQueued=2792388532295, SyncStart=2792395389144, IssueDrawCommandsStart=2792395417333, SwapBuffers=2792400972400, FrameCompleted=2792406541791, DequeueBufferDuration=2105299, QueueBufferDuration=1893634, GpuCompleted=2674296000492, 
I/PlayCore(10008): UID: [10157]  PID: [10008] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
I/PlayCore(10008): UID: [10157]  PID: [10008] ReviewService : linkToDeath
I/PlayCore(10008): UID: [10157]  PID: [10008] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
I/InAppReviewPlugin(10008): onComplete: Successfully requested review flow
I/PlayCore(10008): UID: [10157]  PID: [10008] ReviewService : Unbind from service.
I/InAppReviewPlugin(10008): onMethodCall: requestReview
I/InAppReviewPlugin(10008): requestReview: called
I/InAppReviewPlugin(10008): noContextOrActivity: called
I/InAppReviewPlugin(10008): launchReviewFlow: called
I/InAppReviewPlugin(10008): noContextOrActivity: called
I/Choreographer(10008): Skipped 421 frames!  The application may be doing too much work on its main thread.
I/Choreographer(10008): Skipped 46 frames!  The application may be doing too much work on its main thread.
W/freelance.topu(10008): JNI critical lock held for 20.520ms on Thread[50,tid=10119,Runnable,Thread*=0xd9c27610,peer=0x133c23b8,"FirestoreWorker"]
W/freelance.topu(10008): JNI critical lock held for 16.043ms on Thread[58,tid=10187,Runnable,Thread*=0xd9c38e10,peer=0x130000e0,"Binder:10008_5"]
W/freelance.topu(10008): JNI critical lock held for 26.623ms on Thread[50,tid=10119,Runnable,Thread*=0xd9c27610,peer=0x133c23b8,"FirestoreWorker"]
I/Choreographer(10008): Skipped 88 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer(10008): Davey! duration=2571ms; Flags=1, IntendedVsync=2847777758036, Vsync=2849244424644, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=2849268917376, AnimationStart=2849268919785, PerformTraversalsStart=2849268920022, DrawStart=2849558635078, SyncQueued=2849686024483, SyncStart=2850063876301, IssueDrawCommandsStart=2850194644251, SwapBuffers=2850629490407, FrameCompleted=2850726751983, DequeueBufferDuration=5949375, QueueBufferDuration=38426634, GpuCompleted=2675663163585, 
E/AndroidRuntime(10977): FATAL EXCEPTION: main
E/AndroidRuntime(10977): Process: com.google.android.setupwizard, PID: 10977
E/AndroidRuntime(10977): java.lang.RuntimeException: Unable to create application com.google.android.setupwizard.SetupWizardApplication: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/AndroidRuntime(10977): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
E/AndroidRuntime(10977): 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
E/AndroidRuntime(10977): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
E/AndroidRuntime(10977): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10977): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(10977): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(10977): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10977): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(10977): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(10977): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/AndroidRuntime(10977): 	at com.google.android.setupwizard.SetupWizardApplication.onCreate(PG:8)
E/AndroidRuntime(10977): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
E/AndroidRuntime(10977): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
E/AndroidRuntime(10977): 	... 8 more
`

</details>

**Comment by eeoom** [comment]
Hi!

As my plugin is on top of the plugin in_app_review this might help you: https://github.com/britannio/in_app_review/issues/56

Best
Stefan

**Comment by gupta-shrinath** [comment]
Hi @ankit-agrawal-berlin I don't particular remember everything but you can release your build to a internal beta tester and check there. I hope it helps.
